services:
  db:
    image: mysql:8.4
    container_name: kes-mysql

    environment:
      MYSQL_DATABASE: kes
      MYSQL_USER: kes
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - kes_mysql_data:/var/lib/mysql

    restart: unless-stopped

volumes:
  kes_mysql_data: